export const projects = [
  {
    title: "DiagnoCare",
    description: "Utilize CNN(Convolution Neural Networks) and Machine Learning algo- rithms to diagnose diseases such as Diabetes, Lung cancer, Brain tumors, and Alzheimer’s disease through numerical data and MRI images.",
    image: '/images/1.jpeg',
    tags: ['VGG19', 'Transfer Learning', 'CNN', 'Machine Learning' , 'ReactJs' , 'Flask' , 'JWT' ],
    source: 'https://github.com/desaimann37/DiagnoCare',
    visit: 'https://diagno-care.vercel.app/',
    id: 0,
  },
  {
    title: "Hand Gesture Recognition",
    description: "A hand gesture recognition system automates tasks through finger movements.Key functions include volume con- trol, virtual painting, virtual mouse, and hand tracking using OpenCV.",
    image: '/images/2.jpeg',
    tags: ['Python', 'Flask' , 'OpenCV' , 'MediaPipe' , 'PyAutoGUI'], 
    source: 'https://github.com/desaimann37/Hand_Gesture_Recognition',
    // visit: 'https://google.com',
    id: 1,
  },
  {
    title: "Movie Poster Genre Classification",
    description: "Developed a classification model for movie posters using a Deep Neural Network (YOLOv8x). Classified movie posters into four distinct genres: Action, Horror, Romance, and Animation.Achieved an top1 accuracy of 92.6% using 512x512 grayscale images as input.",
    image: '/images/3.jpeg',
    tags: ["YOLOv8x", 'Deep Learning', 'Python', 'OpenCV' , 'Image Processing' , 'CNN'],
    source: 'https://github.com/desaimann37/YOLO',
    // visit: 'https://google.com',
    id: 2,
  },
  {
    title: "Gaming With JS",
    description: "Fight game developed using JavaScript and SoundJS library. The game features a player and an enemy with a health bar. The player can attack the enemy and vice versa. The game ends when either the player or the enemy’s health bar reaches zero.",
    image: '/images/4.jpeg',
    tags: ['JavaScript', 'HTML', 'CSS', 'SoundJS'],
    source: 'https://github.com/desaimann37/NewFightWithSoundJS.github.io',
    visit: 'https://desaimann37.github.io/NewFightWithSoundJS.github.io/',
    id: 3,
  },
  {
    title: "Spotify Clone",
    description: "Spotify clone app that allows users to search for songs, play them, and view the album cover. The app uses the Spotify API to fetch data and display it to the user.",
    image: '/images/5.jpg',
    tags: ['ReactJs' , 'Spotify API' , 'Material UI'],
    source: 'https://github.com/desaimann37/spotify-clone-app2',
    visit: 'https://www.youtube.com/watch?v=wQ7DLU2PRzw',
    id: 4,
  },
  {
    title: "Inventory Management System",
    description: "Inventory Management System that has 4 features which includes purchase , buyback , writeoff , and maintenance of products. The system is built using MERN stack and uses JWT for authentication.",
    image: '/images/6.jpeg',
    tags: ['MongoDB', 'ExpressJs' , 'ReactJs', 'NodeJs'],
    source: 'https://github.com/desaimann37/Sem_5_IMS',
    id : 5,
  },
  {
    title: "Dog vs Cat Classifier",
    description: " A deep learning model that classifies images of dogs and cats using a Convolutional Neural Network (CNN) and Transfer Learning. The model is trained on the Kaggle dataset and achieves an accuracy of 97.82%.",
    image: '/images/7.jpg',
    tags: ['Python', 'CNN', 'Deep Learning' , 'Transfer Learning'],
    source: 'https://github.com/desaimann37/Deep-Learning/blob/main/CatVSDog_Classification.ipynb',
    id : 6,
  },
  {
    title: "Food Delivery System",
    description: "Food Delivery System that allows users to order food from multiple restaurants. The system is built using Dart and Flutter and uses Firebase for authentication and database management.",
    image: '/images/8.jpeg',
    tags: ['Dart', 'Flutter', 'Firebase'],
    source: 'https://github.com/desaimann37/Food-Delivery-System',
    id : 7,
  },
  {
    title: "Blogging Website",
    description: "Blogging Website that allows users to write, edit, and delete blogs. The website is built using Spring Boot , Rest API , and JWT for authentication.",
    image: '/images/9.png',
    tags: ['Spring Boot', 'Java', 'JWT', 'Hibernate' , 'Rest API' , 'MySQL' , 'Spring Security'],
    source: 'https://github.com/desaimann37/Sem_4_JavaProject_BlogApplication',
    id : 8,
  },
  {
    title: "Next Word Predictor using LSTM",
    description: "Next Word Predictor that uses a Long Short-Term Memory (LSTM) model to predict the next word in a sentence. The model is trained on the Kaggle dataset and achieves an accuracy of 90.2%.",
    image: '/images/10.png',
    tags: ['Python', 'LSTM', 'Deep Learning', 'Natural Language Processing'],
    source: 'https://github.com/desaimann37/Deep-Learning/blob/main/Next_Word_Predictor_LSTM.ipynb',
    id : 9,
  },
  {
    title: "Handwritten Digit Recognition",
    description: "Handwritten Digit Recognition using a Convolutional Neural Network (CNN) and Transfer Learning. The model is trained on the MNIST dataset and achieves an accuracy of 98.3%.",
    image: '/images/11.png',
    tags: ['Python', 'CNN', 'Deep Learning', 'Transfer Learning'],
    source: 'https://github.com/desaimann37/Deep-Learning/blob/main/handwritten_neural_network.ipynb',
    id : 10,
  }
].sort((a, b) => a.id - b.id);

export const TimeLineData = [
  { year: 2019, text: 'SSC 10th Board - 89%', },
  { year: 2021, text: 'HSC 12th Board - 85%', },
  { year: 2024, text: 'Started my Computer Science journey at DDU - Avg CGPA : 8.46', },
];